### ISSUE TITLE
crash: Inappropriate ioctl for device 

### ISSUE THREAD

**Issue by mikeggh** [Blightmud/Blightmud#833] opened 2023-06-30 00:19 UTC
**Describe the bug**
Crash..

I'm compiling using docker i386 debian so i can use blightmud on iSH on iphone... Its been a mission, sorta...
rustix had a situation and they had just fixed it today.  Check the docker file..

i *think* ability to disable sound could help, but i am not positive, you can reproduce...
also before the screenshot:
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default

**To Reproduce**
Dockerfile:
FROM i386/debian:latest as builder
ARG http_proxy
ARG https_proxy
RUN apt-get update
RUN apt-get -y install build-essential libclang-dev pkg-config libssl-dev libasound2-dev git

RUN git clone --depth 1 https://github.com/Blightmud/Blightmud

RUN apt-get -y install wget
RUN wget https://static.rust-lang.org/rustup/dist/i686-unknown-linux-gnu/rustup-init
RUN chmod +x rustup-init
RUN ./rustup-init -y --default-host i686-unknown-linux-gnu

WORKDIR ./Blightmud

#fixed on 6/29/23 for rustix bug
RUN /root/.cargo/bin/cargo update -p rustix:0.37.19 --precise 0.37.21
RUN /root/.cargo/bin/cargo build -r

CMD ["./target/release/blightmud"]

------------------------------
docker build -t bmud --build-arg http_proxy=http://172.20.10.1:8888 --build-arg https_proxy=http://172.20.10.1:8888 ./
docker run bmud

**What terminal are you using?**
Windows Terminal

**What mud were you playing?**
Haven't gotten this far..

**Screenshots**
![image](https://github.com/Blightmud/Blightmud/assets/125227868/c730467d-6279-4ac3-9585-92322ca9b2f0)

**Comment by cpu** [comment] 2023-06-30 13:03
Hi there @mikeggh,

Could you provide the `CRASH_LOG` file mentioned in your screenshot?

**Comment by mikeggh** [comment] 2023-06-30 16:35
Yes, sorry meant to do that too!
name = "blightmud"
operating_system = "Debian 12.0.0 [32-bit]"
crate_version = "5.3.0"
explanation = """
Panic occurred in file 'src/main.rs' at line 85
"""
cause = "Panic: Inappropriate ioctl for device (os error 25)"
method = "Panic"
backtrace = """

   0: 0x566c24b8 - blightmud::main::hc93d80f4bc6ecb06
   1: 0x566c0804 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha93044227f42e94a
   2: 0x566c079e - std::rt::lang_start::{{closure}}::h62377d44e84de6a1
   3: 0x56e056bf - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd5f1320e8a8a6a3e
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287
             - std::panicking::try::do_call::h7d34e8712f7a43d8
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485
             - std::panicking::try::h426c911448fe9eb8
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449
             - std::panic::catch_unwind::hc1fcb6be06898363
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140
             - std::rt::lang_start_internal::{{closure}}::hec7699f3a59e3eff
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148
             - std::panicking::try::do_call::ha1ac54e954d26f89
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485
             - std::panicking::try::h99927d6fd75aeec6
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449
             - std::panic::catch_unwind::hbec8edb0c5f02515
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140
             - std::rt::lang_start_internal::h11e13b3a1eebac8b
            at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148
   4: 0x566c25b8 - main
   5: 0xf743f295 - <unresolved>
   6: 0xf743f358 - __libc_start_main
   7: 0x566be4f7 - _start
   8:    0x0 - <unresolved>"""

**Comment by cpu** [comment] 2023-06-30 16:45
@mikeggh Thank you!

I think the ALSA related warnings you see on startup are unrelated (I see similar running `blightmud` on a headless server w/o sound).

> cause = "Panic: Inappropriate ioctl for device (os error 25)"

This looks like the root cause of the issue so I've updated the title. I suspect it's due to the iSH terminal you're running Blight under, but it will need more investigation.

Unrelated: but have you considered running `blightmud` on a remote linux server and connecting to it from your iphone using a `ssh` client? That approach is likely to be a nicer user experience (at the cost of having to maintain a remote server). Something to think about while this bug is unresolved :-)

**Comment by mikeggh** [comment] 2023-06-30 21:25
I understand.. I'm new to rust but may take a crack at it.. but yes I can't expect devs to try to solve every situation an emulated kernel may surface..
Thanks for your time!

**Comment by Xandaros** [comment] 2023-07-01 12:08
Try running it with `docker run -t`

It looks to me like running it with just `docker run`, it doesn't actually allocate a tty and just hooks up stdin, stdout, and stderr. This works fine for CLI applications, but TUI applications (like Blightmud) need a tty to function.

**Comment by cpu** [comment] 2023-07-07 18:28
@mikeggh Did the suggestion to try `docker run` with `--tty` to get a pseudo-TTY end up working out? It would be pretty sweet if that workaround means there's no changes needed on the Blightmud side.

**Comment by mikotaichou** [comment] 2023-10-02 20:31
@mikeggh - I have a pipeline for amd64 and arm64 images that I can add another architecture to, the images work on those machines, if you have an arch you would like me to test, please let me know!

**Comment by LiquidityC** [comment] 2023-10-05 08:19
I'll go ahead and close this. I think the answers and data that has been provided do contain the solution for the original problem.

**Closed by LiquidityC** 2023-10-05 08:19 UTC
Labels: bug
