### ISSUE TITLE
hunspell-rs dependency fails to link on MacOS

### ISSUE THREAD

**Issue by rdaum** [Blightmud/Blightmud#797] opened 2023-04-26 01:24 UTC
I wanted to give Blightmud a whirl, so tried both `cargo install` and a `cargo run` from the sources, but linkage failed on my M1 Macbook Pro.

I bisected back to 5.0.0 and it linked and ran fine, but 5.1.0 did not. Looking at the linker error and the differences to 5.1.0 I noticed the Hunspell-rs dependency.  It seems like this fails to link in C++ linkage phase. Not sure if this is particular to my box (`Ventura 13.3.1`, XCode `14.3.0.0.1.1679647830` ) but ultimately seems to boil down to:

`  = note: Undefined symbols for architecture arm64:`

Attaching a log of the link fail.
[build-fail.txt](https://github.com/Blightmud/Blightmud/files/11328035/build-fail.txt)

**Comment by cpu** [comment] 2023-04-26 01:45
Hi there, 

Sorry to hear the hunspell feature is causing you trouble. Thanks for the log.

I was able to build with a from-scratch rustup/clone on a MacBook Air (M1, 2020) running MacOS Monterey 12.4 the other day :thinking: It was a borrowed machine so I'm not sure if I was lucky and it happened to already have some pre-existing system wide hunspell that avoided the problem. Alternatively, perhaps it's Ventura specific? 

My understanding is the hunspell-rs and hunspell-sys crates should be falling back to a vendored build of libhunspell if a system-wide one isn't available. It shouldn't be necessary but I wonder if using homebrew to install hunspell would make any difference.

**Comment by rdaum** [comment] 2023-04-26 01:57
Thanks for the quick response.  I tried just now doing a `brew install hunspell` and then a run of Blightmud off HEAD of master and it failed with the same failure.

Following the link failures back it seems to be quite basic C++ standard library pieces missing:

`  "std::__throw_bad_array_new_length()", referenced from:`

`"std::basic_istream<char, std::char_traits<char>>& std::getline<char, std::char_traits<char>, std::allocator<char>>(std::basic_istream<char, std::char_traits<char>>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, char)", referenced from:`

`            "std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char>>::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::_Ios_Openmode)", referenced from:
                line_tok(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, char) in libhunspell_sys-e2378a5a53cb8476.rlib(csutil.o)`

Fairly surprising; I typically only do Rust and Julia dev on this machine, so I can't make any claims about its C++ environment, but it's a fairly up-to-date in most ways. 

So yeah, could be bespoke to my machine. Hard to say. I wonder if it'd be worth trying a GitHub Action which compiles against ARM64 Mac OS. 

https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/

**Comment by cpu** [comment] 2023-04-26 02:07
Quite odd! Thanks for linking to the Ventura runner availability announcement. That's a good idea worth pursuing.

There's a 'macos-latest' runner in the matrix today but I think because the Ventura runners are beta we need to opt in explicitly.

**Comment by LiquidityC** [comment] 2023-04-26 04:28
Adding Mac arm to the build matrix should be quite easy.

**Comment by cpu** [comment] 2023-04-26 13:53
> Adding Mac arm to the build matrix should be quite easy.

I tried the same thing you did in https://github.com/Blightmud/Blightmud/pull/798 and noticed two things:

1. The Ventura build passes.
2. It's x86_64, not arm64.

This makes me think it's possibly an arm64+ventura problem. Doing some quick googling it didn't seem possible to get an arm64 M1 or M2 runner without self-hosting or looking at other CI services :-/

**Comment by LiquidityC** [comment] 2023-04-27 06:19
> This makes me think it's possibly an arm64+ventura problem. Doing some quick googling it didn't seem possible to get an arm64 M1 or M2 runner without self-hosting or looking at other CI services :-/

Same conclusion I've come to. I couldn't even find one that's free. It's not the first time we run into this new apple-silicon problem.

**Comment by LiquidityC** [comment] 2023-04-27 06:22
Re-reasing the comments...

> ` = note: Undefined symbols for architecture arm64:`

Makes me think it's the hunspell shared lib that isn't built on arm64. Which is confusing. Hunspell in blightmud should build its own lib. But does it build the hunspell shared libs as well or are those expected to be provided by the system?

**Comment by cpu** [comment] 2023-04-27 13:35
We're using the `bundled` feature of `hunspell-sys`:
https://github.com/Blightmud/Blightmud/blob/d0a449ae982b294c8386c22d2eea983005a46011/Cargo.toml#L47

It's [described](https://github.com/euclio/hunspell-sys#building) as building a bundled copy with the `cc` crate and statically linking.

I'm finding it challenging to support an OS I don't run and an architecture I can't test on. WDYT about making the hunspell dependency and API a feature-flag that's on by default, but that can be skipped with `cargo build --no-default-feature --features tts` for users that run into trouble like this? They'll lose out on the spellchecking API but would have a build that otherwise works.

**Comment by cpu** [comment] 2023-04-28 00:03
> WDYT about making the hunspell dependency and API a feature-flag that's on by default

In case that's interesting: https://github.com/Blightmud/Blightmud/pull/801

It might also be worthwhile to open an issue upstream with `hunspell-sys` to see if the maintainer of that crate has any ideas. I have a hockey game to get back to watching but I can take care of that tomorrow evening :ice_hockey: :maple_leaf:

**Comment by cpu** [comment] 2023-04-28 19:10
@rdaum You should be able to build tip of `dev` with `--no-default-features` to avoid the hunspell dependency at the cost of not getting the spellcheck APIs.

**Comment by cpu** [comment] 2023-05-10 13:18
I opened the upstream issue w/ hunspell-sys. Since there's a feature flag to work around the problem I think there's nothing left to do on the Blightmud side unless there's some new information or one of us can reproduce. I'm going to close this issue for now.

Thanks!

**Closed by cpu** 2023-05-10 13:18 UTC
Labels: bug
